-- Creating a table to store ISRO space mission data
CREATE TABLE isro_space_missions (
    mission_id INT PRIMARY KEY,
    mission_name VARCHAR(100),
    launch_date DATE,
    launch_vehicle VARCHAR(50),
    orbit_type VARCHAR(50),
    application VARCHAR(100),
    outcome VARCHAR(50),
    launch_site VARCHAR(100),
    payload VARCHAR(100)
);

-- Inserting data for ISRO missions from 1963 to August 2025
INSERT INTO isro_space_missions (mission_id, mission_name, launch_date, launch_vehicle, orbit_type, application, outcome, launch_site, payload) VALUES
(1, 'Nike-Apache', '1963-11-21', 'Nike-Apache', 'Suborbital', 'Sounding Rocket', 'Launch successful', 'Thumba Equatorial Rocket Launching Station', 'Scientific Payload'),
(2, 'Aryabhata', '1975-04-19', 'Kosmos-3M', 'LEO', 'Experimental', 'Launch successful', 'Kapustin Yar, USSR', 'Aryabhata Satellite'),
(3, 'Bhaskara-I', '1979-06-07', 'Kosmos-3M', 'LEO', 'Earth Observation', 'Launch successful', 'Kapustin Yar, USSR', 'Bhaskara-I Satellite'),
(4, 'Rohini-1', '1980-07-18', 'SLV-3', 'LEO', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Rohini-1 Satellite'),
(5, 'APPLE', '1981-06-19', 'Ariane-1', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'APPLE Satellite'),
(6, 'Bhaskara-II', '1981-11-20', 'Kosmos-3M', 'LEO', 'Earth Observation', 'Launch successful', 'Kapustin Yar, USSR', 'Bhaskara-II Satellite'),
(7, 'INSAT-1A', '1982-04-10', 'Delta 3910', 'GSO', 'Communication', 'Launch successful', 'Cape Canaveral, USA', 'INSAT-1A Satellite'),
(8, 'RS-D2', '1983-04-17', 'SLV-3', 'LEO', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Rohini Satellite'),
(9, 'INSAT-1B', '1983-08-30', 'Space Shuttle', 'GSO', 'Communication', 'Launch successful', 'Kennedy Space Center, USA', 'INSAT-1B Satellite'),
(10, 'IRS-1A', '1988-03-17', 'Vostok', 'SSPO', 'Earth Observation', 'Launch successful', 'Baikonur, USSR', 'IRS-1A Satellite'),
(11, 'SROSS-2', '1988-07-13', 'ASLV', 'LEO', 'Experimental', 'Launch unsuccessful', 'Satish Dhawan Space Centre, Sriharikota', 'SROSS-2 Satellite'),
(12, 'INSAT-1C', '1988-07-21', 'Ariane-3', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-1C Satellite'),
(13, 'INSAT-1D', '1990-06-12', 'Delta 4925', 'GSO', 'Communication', 'Launch successful', 'Cape Canaveral, USA', 'INSAT-1D Satellite'),
(14, 'IRS-1B', '1991-08-29', 'Vostok', 'SSPO', 'Earth Observation', 'Launch successful', 'Baikonur, USSR', 'IRS-1B Satellite'),
(15, 'SROSS-C', '1992-05-20', 'ASLV', 'LEO', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'SROSS-C Satellite'),
(16, 'INSAT-2A', '1992-07-10', 'Ariane-44L', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-2A Satellite'),
(17, 'INSAT-2B', '1993-07-23', 'Ariane-44L', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-2B Satellite'),
(18, 'IRS-1E', '1993-09-20', 'PSLV-D1', 'SSPO', 'Earth Observation', 'Launch unsuccessful', 'Satish Dhawan Space Centre, Sriharikota', 'IRS-1E Satellite'),
(19, 'SROSS-C2', '1994-05-04', 'ASLV', 'LEO', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'SROSS-C2 Satellite'),
(20, 'IRS-P2', '1994-10-15', 'PSLV-D2', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRS-P2 Satellite'),
(21, 'IRS-1C', '1995-12-28', 'Molniya', 'SSPO', 'Earth Observation', 'Launch successful', 'Baikonur, Kazakhstan', 'IRS-1C Satellite'),
(22, 'IRS-P3', '1996-03-21', 'PSLV-D3', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRS-P3 Satellite'),
(23, 'IRS-1D', '1997-09-29', 'PSLV-C1', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRS-1D Satellite'),
(24, 'INSAT-2E', '1999-04-03', 'Ariane-42P', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-2E Satellite'),
(25, 'Oceansat-1', '1999-05-26', 'PSLV-C2', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Oceansat-1 Satellite'),
(26, 'INSAT-3B', '2000-03-21', 'Ariane-5G', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-3B Satellite'),
(27, 'GSAT-1', '2001-04-18', 'GSLV-D1', 'GTO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-1 Satellite'),
(28, 'TES', '2001-10-22', 'PSLV-C3', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'TES Satellite'),
(29, 'INSAT-3C', '2002-01-24', 'Ariane-42L', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-3C Satellite'),
(30, 'Kalpana-1', '2002-09-12', 'PSLV-C4', 'GSO', 'Meteorological', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Kalpana-1 Satellite'),
(31, 'INSAT-3A', '2003-04-10', 'Ariane-5G', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-3A Satellite'),
(32, 'GSAT-2', '2003-05-08', 'GSLV-D2', 'GTO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-2 Satellite'),
(33, 'INSAT-3E', '2003-09-28', 'Ariane-5G', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-3E Satellite'),
(34, 'RESOURCESAT-1', '2003-10-17', 'PSLV-C5', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RESOURCESAT-1 Satellite'),
(35, 'EDUSAT', '2004-09-20', 'GSLV-F01', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'EDUSAT Satellite'),
(36, 'CARTOSAT-1', '2005-05-05', 'PSLV-C6', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'CARTOSAT-1 Satellite'),
(37, 'HAMSAT', '2005-05-05', 'PSLV-C6', 'SSPO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'HAMSAT Satellite'),
(38, 'INSAT-4A', '2005-12-22', 'Ariane-5GS', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-4A Satellite'),
(39, 'INSAT-4C', '2006-07-10', 'GSLV-F02', 'GTO', 'Communication', 'Launch unsuccessful', 'Satish Dhawan Space Centre, Sriharikota', 'INSAT-4C Satellite'),
(40, 'CARTOSAT-2', '2007-01-10', 'PSLV-C7', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'CARTOSAT-2 Satellite'),
(41, 'SRE-1', '2007-01-10', 'PSLV-C7', 'SSPO', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'SRE-1 Capsule'),
(42, 'INSAT-4B', '2007-03-12', 'Ariane-5ECA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'INSAT-4B Satellite'),
(43, 'INSAT-4CR', '2007-09-02', 'GSLV-F04', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'INSAT-4CR Satellite'),
(44, 'CARTOSAT-2A', '2008-04-28', 'PSLV-C9', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'CARTOSAT-2A Satellite'),
(45, 'Chandrayaan-1', '2008-10-22', 'PSLV-C11', 'Lunar', 'Planetary Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Chandrayaan-1 Orbiter'),
(46, 'RISAT-2', '2009-04-20', 'PSLV-C12', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RISAT-2 Satellite'),
(47, 'Oceansat-2', '2009-09-23', 'PSLV-C14', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Oceansat-2 Satellite'),
(48, 'GSAT-4', '2010-04-15', 'GSLV-D3', 'GTO', 'Communication', 'Launch unsuccessful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-4 Satellite'),
(49, 'CARTOSAT-2B', '2010-07-12', 'PSLV-C15', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'CARTOSAT-2B Satellite'),
(50, 'HYLAS', '2010-11-27', 'Ariane-5ECA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'HYLAS Satellite'),
(51, 'GSAT-5P', '2010-12-25', 'GSLV-F06', 'GTO', 'Communication', 'Launch unsuccessful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-5P Satellite'),
(52, 'Resourcesat-2', '2011-04-20', 'PSLV-C16', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Resourcesat-2 Satellite'),
(53, 'GSAT-8', '2011-05-21', 'Ariane-5VA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-8 Satellite'),
(54, 'GSAT-12', '2011-07-15', 'PSLV-C17', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-12 Satellite'),
(55, 'Megha-Tropiques', '2011-10-12', 'PSLV-C18', 'LEO', 'Climate & Environment', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Megha-Tropiques Satellite'),
(56, 'RISAT-1', '2012-04-26', 'PSLV-C19', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RISAT-1 Satellite'),
(57, 'SPOT-6', '2012-09-09', 'PSLV-C21', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'SPOT-6 Satellite'),
(58, 'GSAT-10', '2012-09-29', 'Ariane-5ECA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-10 Satellite'),
(59, 'SARAL', '2013-02-25', 'PSLV-C20', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'SARAL Satellite'),
(60, 'IRNSS-1A', '2013-07-01', 'PSLV-C22', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1A Satellite'),
(61, 'INSAT-3D', '2013-07-26', 'Ariane-5ECA', 'GSO', 'Meteorological', 'Launch successful', 'Kourou, French Guiana', 'INSAT-3D Satellite'),
(62, 'Mangalyaan', '2013-11-05', 'PSLV-C25', 'Martian', 'Planetary Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Mars Orbiter'),
(63, 'GSAT-14', '2014-01-05', 'GSLV-D5', 'GTO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-14 Satellite'),
(64, 'IRNSS-1B', '2014-04-04', 'PSLV-C24', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1B Satellite'),
(65, 'IRNSS-1C', '2014-10-16', 'PSLV-C26', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1C Satellite'),
(66, 'GSAT-16', '2014-12-07', 'Ariane-5ECA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-16 Satellite'),
(67, 'CARE', '2014-12-18', 'LVM3-X', 'Suborbital', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'CARE Capsule'),
(68, 'IRNSS-1D', '2015-03-28', 'PSLV-C27', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1D Satellite'),
(69, 'DMC3', '2015-07-10', 'PSLV-C28', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'DMC3 Satellites'),
(70, 'GSAT-6', '2015-08-27', 'GSLV-D6', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-6 Satellite'),
(71, 'ASTROSAT', '2015-09-28', 'PSLV-C30', 'SSPO', 'Scientific Research', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'ASTROSAT Satellite'),
(72, 'GSAT-15', '2015-11-11', 'Ariane-5VA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-15 Satellite'),
(73, 'TeLEOS-1', '2015-12-16', 'PSLV-C29', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'TeLEOS-1 Satellite'),
(74, 'IRNSS-1E', '2016-01-20', 'PSLV-C31', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1E Satellite'),
(75, 'IRNSS-1F', '2016-03-10', 'PSLV-C32', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1F Satellite'),
(76, 'IRNSS-1G', '2016-04-28', 'PSLV-C33', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1G Satellite'),
(77, 'RLV-TD', '2016-05-23', 'RLV-TD', 'Suborbital', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RLV-TD Vehicle'),
(78, 'Cartosat-2', '2016-06-22', 'PSLV-C34', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Cartosat-2 Satellite'),
(79, 'Scramjet-TD', '2016-08-28', 'Scramjet', 'Suborbital', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Scramjet Engine'),
(80, 'INSAT-3DR', '2016-09-08', 'GSLV-F05', 'GSO', 'Climate & Environment', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'INSAT-3DR Satellite'),
(81, 'SCATSAT-1', '2016-09-26', 'PSLV-C35', 'SSPO', 'Climate & Environment', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'SCATSAT-1 Satellite'),
(82, 'GSAT-18', '2016-10-05', 'Ariane-5ECA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-18 Satellite'),
(83, 'RESOURCESAT-2A', '2016-12-07', 'PSLV-C36', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RESOURCESAT-2A Satellite'),
(84, 'Cartosat-2 Series', '2017-02-15', 'PSLV-C37', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Cartosat-2 Series Satellite'),
(85, 'GSAT-9', '2017-05-05', 'GSLV-F09', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-9 Satellite'),
(86, 'GSAT-19', '2017-06-05', 'GSLV Mk III-D1', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-19 Satellite'),
(87, 'Cartosat-2 Series', '2017-06-23', 'PSLV-C38', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Cartosat-2 Series Satellite'),
(88, 'GSAT-17', '2017-06-29', 'Ariane-5VA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-17 Satellite'),
(89, 'IRNSS-1H', '2017-08-31', 'PSLV-C39', 'GSO', 'Navigation', 'Launch unsuccessful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1H Satellite'),
(90, 'Cartosat-2 Series', '2018-01-12', 'PSLV-C40', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Cartosat-2 Series Satellite'),
(91, 'GSAT-6A', '2018-03-29', 'GSLV-F08', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-6A Satellite'),
(92, 'IRNSS-1I', '2018-04-12', 'PSLV-C41', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'IRNSS-1I Satellite'),
(93, 'HysIS', '2018-11-29', 'PSLV-C43', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'HysIS Satellite'),
(94, 'GSAT-29', '2018-11-14', 'GSLV Mk III-D2', 'GTO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-29 Satellite'),
(95, 'GSAT-11', '2018-12-05', 'Ariane-5VA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-11 Satellite'),
(96, 'GSAT-7A', '2018-12-19', 'GSLV-F11', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'GSAT-7A Satellite'),
(97, 'Microsat-R', '2019-01-24', 'PSLV-C44', 'SSPO', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Microsat-R Satellite'),
(98, 'GSAT-31', '2019-02-06', 'Ariane-5VA', 'GTO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-31 Satellite'),
(99, 'EMISAT', '2019-04-01', 'PSLV-C45', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'EMISAT Satellite'),
(100, 'RISAT-2B', '2019-05-22', 'PSLV-C46', 'LEO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RISAT-2B Satellite'),
(101, 'Chandrayaan-2', '2019-07-22', 'GSLV Mk III-M1', 'Lunar', 'Planetary Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Chandrayaan-2 Orbiter'),
(102, 'Cartosat-3', '2019-11-27', 'PSLV-C47', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Cartosat-3 Satellite'),
(103, 'RISAT-2BR1', '2019-12-11', 'PSLV-C48', 'LEO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RISAT-2BR1 Satellite'),
(104, 'GSAT-30', '2020-01-17', 'Ariane-5VA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-30 Satellite'),
(105, 'EOS-01', '2020-11-07', 'PSLV-C49', 'LEO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'EOS-01 Satellite'),
(106, 'CMS-01', '2020-12-17', 'PSLV-C50', 'GSO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'CMS-01 Satellite'),
(107, 'Amazonia-1', '2021-02-28', 'PSLV-C51', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Amazonia-1 Satellite'),
(108, 'EOS-03', '2021-08-12', 'GSLV-F10', 'GTO', 'Earth Observation', 'Launch unsuccessful', 'Satish Dhawan Space Centre, Sriharikota', 'EOS-03 Satellite'),
(109, 'EOS-04', '2022-02-14', 'PSLV-C52', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'EOS-04 Satellite'),
(110, 'INS-2TD', '2022-02-14', 'PSLV-C52', 'SSPO', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'INS-2TD Satellite'),
(111, 'GSAT-24', '2022-06-23', 'Ariane-5VA', 'GSO', 'Communication', 'Launch successful', 'Kourou, French Guiana', 'GSAT-24 Satellite'),
(112, 'EOS-02', '2022-08-07', 'SSLV-D1', 'SSPO', 'Earth Observation', 'Launch unsuccessful', 'Satish Dhawan Space Centre, Sriharikota', 'EOS-02 Satellite'),
(113, 'OneWeb India-1', '2022-10-23', 'LVM3-M2', 'LEO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'OneWeb Satellites'),
(114, 'EOS-06', '2022-11-26', 'PSLV-C54', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'EOS-06 Satellite'),
(115, 'Anand', '2022-11-26', 'PSLV-C54', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Anand Satellite'),
(116, 'Thybolt', '2022-11-26', 'PSLV-C54', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Thybolt Satellite'),
(117, 'INS-2B', '2022-11-26', 'PSLV-C54', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'INS-2B Satellite'),
(118, 'EOS-07', '2023-02-10', 'SSLV-D2', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'EOS-07 Satellite'),
(119, 'OneWeb India-2', '2023-03-26', 'LVM3-M3', 'LEO', 'Communication', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'OneWeb Satellites'),
(120, 'RLVLEX', '2023-04-02', 'RLV', 'Suborbital', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RLVLEX Vehicle'),
(121, 'TeLEOS-2', '2023-04-22', 'PSLV-C55', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'TeLEOS-2 Satellite'),
(122, 'NVS-01', '2023-05-29', 'GSLV-F12', 'GSO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'NVS-01 Satellite'),
(123, 'Chandrayaan-3', '2023-07-14', 'LVM3-M4', 'Lunar', 'Planetary Observation', 'Launch sucessful', 'Satish Dhawan Space Centre, Sriharikota', 'Chandrayaan-3 Lander'),
(124, 'DS-SAR', '2023-07-30', 'PSLV-C56', 'SSPO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'DS-SAR Satellite'),
(125, 'Aditya-L1', '2023-09-02', 'PSLV-C57', 'L1', 'Solar Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Aditya-L1 Observatory'),
(126, 'TV-D1', '2023-10-21', 'TV-D1', 'Suborbital', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Gaganyaan Test Vehicle'),
(127, 'XPoSat', '2024-01-01', 'PSLV-C58', 'LEO', 'Scientific Research', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'XPoSat Satellite'),
(128, 'INSAT-3DS', '2024-02-17', 'GSLV-F14', 'GSO', 'Meteorological', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'INSAT-3DS Satellite'),
(129, 'RLVLEX-02', '2024-03-22', 'RLV', 'Suborbital', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RLVLEX-02 Vehicle'),
(130, 'RLVLEX-03', '2024-06-23', 'RLV', 'Suborbital', 'Experimental', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'RLVLEX-03 Vehicle'),
(131, 'Proba-3', '2024-12-05', 'PSLV-C59', 'HEO', 'Technology Demonstration', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'Proba-3 Satellite'),
(132, 'SPADEX, POEM-4', '2024-12-30', 'PSLV-C60', 'LEO', 'In-orbit Docking Experiment', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'SPADEX Satellites'),
(133, 'NVS-02', '2025-01-29', 'GSLV-F15', 'GTO', 'Navigation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'NVS-02 Satellite'),
(134, 'EOS-09', '2025-05-18', 'PSLV-C61', 'SSO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'EOS-09 Satellite'),
(135, 'NISAR', '2025-07-30', 'GSLV-F16', 'SSO', 'Earth Observation', 'Launch successful', 'Satish Dhawan Space Centre, Sriharikota', 'NISAR Satellite');
